import { v4 as uuid } from "uuid";
/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

export const videos = [
  {
    _id : uuid(),
    title : "Vikram",
    thumbnailUrl : "https://i.ytimg.com/vi/OKBMCL-frPU/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBwOVBaXuXOgvwubxOSsBwE3HqlCQ",
    channelImg : "https://yt3.ggpht.com/ytc/AKedOLRSu0SoelpGmqyAj7H-l9AvN_a4GiV145VwyF4yqA=s88-c-k-c0x00ffffff-no-rj",
    views: "35M",
    subscribers : "11.9M",
    videoLength : "02:39",
    ChannelName : "Sony Music South",
    categoryName : "Action",
    youtubeId : "OKBMCL-frPU",
    description : "#VikramTrailer #VikramAudioLaunch #VikramInAction #VIKRAM WORLDWIDE THEATRICAL RELEASE ON JUNE 3RD. ",
  },
  {
    _id : uuid(),
    title : "Black Adam",
    thumbnailUrl : "https://i.ytimg.com/vi/X0tOpBuYasI/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLA9-5tWtozuBOHlemmT_CGpmkQDEg",
    channelImg : "https://yt3.ggpht.com/ytc/AKedOLR8AhEtB7GP7HrKp1mI0gYUu5HSa-HiqIpOkTOF5A=s88-c-k-c0x00ffffff-no-rj",
    views: "8.9M",
    subscribers : "10.5M",
    videoLength : "02:07",
    ChannelName : "Warner Bros.",
    categoryName : "Action",
    youtubeId : "X0tOpBuYasI",
    description : "The world needed a hero, it got #BLACKADAM. Only in theaters October 21. From New Line Cinema, Dwayne Johnson stars in the action adventure “Black Adam.”  The first-ever feature film to explore the story of the DC Super Hero comes to the big screen under the direction of Jaume Collet-Serra (“Jungle Cruise”).",
  },
  {
    _id : uuid(),
    title : "The Gray Man",
    thumbnailUrl: "https://i.ytimg.com/vi/BmllggGO4pM/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDFcWc_bwnHz1Umh2m4J-pv8D6dYw",
    channelImg : "https://yt3.ggpht.com/ytc/AKedOLTZzZv60B1v76eOC7TsEYZD_TMH2-H5KeYxkfXGBQ=s68-c-k-c0x00ffffff-no-rj",
    views: "12M",
    subscribers : "23.7M",
    videoLength : "02:12",
    ChannelName : "Netflix",
    categoryName : "Action",
    youtubeId : "BmllggGO4pM",
    description :
      "Ryan Gosling is THE GRAY MAN and Chris Evans is his psychopathic adversary in the Netflix/AGBO spy thriller directed by Anthony and Joe Russo - available globally July 22 on Netflix.",
  },
  {
    _id : uuid(),
    title : "Bahubali 2 - The Conclusion",
    thumbnailUrl: "https://i.ytimg.com/vi/G62HrubdD6o/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDLmuddshTwWMsGLRuZ2AZ83oRMOw",
    channelImg : "https://yt3.ggpht.com/ytc/AKedOLQ7GkbJMx3cRmxUQyO4UNpmukpq2ptdBMX5J1ogoIU=s88-c-k-c0x00ffffff-no-rj",
    views: "124M",
    subscribers : "9.4M",
    videoLength : "02:25",
    ChannelName : "Dharma Productions",
    categoryName : "Action",
    youtubeId : "G62HrubdD6o",
    description : "The most awaited trailer of the year is finally here. After years of wait, the second instalment to the Baahubali series is ready to hit the theatres. It's bigger, better & grander. Baahubali 2 - The Conclusion in cinemas on 28th April, 2017.",
  },
  {
    _id : uuid(),
    title : "Dune",
    thumbnailUrl : "https://i.ytimg.com/vi/8g18jFHCLXk/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCUwwmyQAXfIaLLPpaJM0TYz7xfAw",
    channelImg : "https://yt3.ggpht.com/ytc/AKedOLR8AhEtB7GP7HrKp1mI0gYUu5HSa-HiqIpOkTOF5A=s88-c-k-c0x00ffffff-no-rj",
    views: "32.1M",
    subscribers : "10.5M",
    videoLength : "03:28",
    ChannelName : "Warner Bros.",
    categoryName : "Sci-Fi",
    youtubeId : "8g18jFHCLXk",
    description : "Oscar nominee Denis Villeneuve (“Arrival,” “Blade Runner 2049”) directs Warner Bros. Pictures and Legendary Pictures’ “Dune,” the big-screen adaptation of Frank Herbert’s seminal bestseller of the same name.",
  },
  {
    _id : uuid(),
    title : "KGF - Chapter 2",
    thumbnailUrl : "https://i.ytimg.com/vi/JKa05nyUmuQ/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCNZoTgaiFK9K_kqa7rmF9pEgbjkA",
    channelImg : "https://yt3.ggpht.com/ytc/AKedOLQ0-Fy-Jar8uziiEmKe6jLw10oHpKeTPInAE22f=s68-c-k-c0x00ffffff-no-rj",
    views: "112M",
    subscribers : "3.64M",
    videoLength : "02:57",
    ChannelName : "Excel Movies",
    categoryName : "Action",
    youtubeId : "JKa05nyUmuQ",
    description : "KGF Chapter 2 releases on 14th April, 2022. Presented by Ritesh Sidhwani, Farhan Akhtar and AA Films. Produced by Vijay Kiragandur under the Banner Hombale Films.",
  },
  {
    _id : uuid(),
    title : "The Batman",
    thumbnailUrl : "https://i.ytimg.com/vi/mqqft2x_Aa4/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCTpgaSN8199NNo06NEo5LebSJNJQ",
    channelImg : "https://yt3.ggpht.com/ytc/AKedOLR8AhEtB7GP7HrKp1mI0gYUu5HSa-HiqIpOkTOF5A=s88-c-k-c0x00ffffff-no-rj",
    views: "54M",
    subscribers : "10.5M",
    videoLength : "02:38",
    ChannelName : "Warner Bros.",
    categoryName : "Action",
    youtubeId : "mqqft2x_Aa4",
    description : "It’s not just a call… It’s a warning.  From Warner Bros. Pictures comes Matt Reeves’ “The Batman,” starring Robert Pattinson in the dual role of Gotham City’s vigilante detective and his alter ego, reclusive billionaire Bruce Wayne. Starring alongside Pattinson (“Tenet,” “The Lighthouse”) as Gotham’s famous and infamous cast of characters are Zoë Kravitz (“Big Little Lies,” “Fantastic Beasts: The Crimes of Grindelwald”) as Selina Kyle; Paul Dano (“Love & Mercy,” “12 Years a Slave”) as Edward Nashton; Jeffrey Wright (“No Time to Die,” “Westworld”) as the GCPD’s James Gordon; John Turturro (the “Transformers” films, “The Plot Against America”) as Carmine Falcone; Peter Sarsgaard (“The Magnificent Seven,” “Interrogation”) as Gotham D.A. Gil Colson; Jayme Lawson (“Farewell Amor”) as mayoral candidate Bella Reál; with Andy Serkis (the “Planet of the Apes” films, “Black Panther”) as Alfred; and Colin Farrell (“The Gentlemen,” “Fantastic Beasts and Where to Find Them”) as Oswald Cobblepot. ",
  },
  {
    _id : uuid(),
    title : "Avatar",
    thumbnailUrl : "https://i.ytimg.com/vi/5PSNL1qE6VY/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDumucY9wAQJLgBwtpsB4T8qnwIwA",
    channelImg : "https://yt3.ggpht.com/ytc/AKedOLS0_xUgI38v9jdvNVywBUODYhgnM0rU3_iJfD0ytQ=s88-c-k-c0x00ffffff-no-rj",
    views: "9.6M",
    subscribers : "4.4M",
    videoLength : "02:28",
    ChannelName : "20th Century Studios",
    categoryName : "Sci-Fi",
    youtubeId : "5PSNL1qE6VY",
    description : "AVATAR takes us to a spectacular world beyond imagination, where a reluctant hero embarks on an epic adventure, ultimately fighting to save the alien world he has learned to call home. James Cameron, the Oscar-winning director of Titanic, first conceived the film 15 years ago, when the means to realize his vision did not exist yet. Now, after four years of production, AVATAR, a live action film with a new generation of special effects, delivers a fully immersive cinematic experience of a new kind, where the revolutionary technology invented to make the film disappears into the emotion of the characters and the sweep of the story.",
  },
  {
    _id : uuid(),
    title : "Interstellar",
    thumbnailUrl : "https://i.ytimg.com/vi/zSWdZVtXT7E/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBdqaDdFnFXiykqpCEVKkkiEYEBcA",
    channelImg : "https://yt3.ggpht.com/ytc/AKedOLR8AhEtB7GP7HrKp1mI0gYUu5HSa-HiqIpOkTOF5A=s88-c-k-c0x00ffffff-no-rj",
    views: "34M",
    subscribers : "1.23M",
    videoLength : "02:54",
    ChannelName : "Warner Bros. UK & Ireland",
    categoryName : "Sci-Fi",
    youtubeId : "zSWdZVtXT7E",
    description : "With our time on Earth coming to an end, a team of explorers undertakes the most important mission in human history: traveling beyond this galaxy to discover whether mankind has a future among the stars.",
  },
  {
    _id : uuid(),
    title : "24",
    thumbnailUrl : "https://i.ytimg.com/vi/wqXE_es_I3M/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAMy_L7wVpj_wXLckkr1jeKnEQ-4g",
    channelImg : "https://yt3.ggpht.com/ytc/AKedOLRUp0TcKUeMztG5NHpuS9-znYCCf3MOjSoJMI-V=s88-c-k-c0x00ffffff-no-rj",
    views: "6.7M",
    subscribers : "404k",
    videoLength : "02:11",
    ChannelName : "2D Entertainment",
    categoryName : "Sci-Fi",
    youtubeId : "wqXE_es_I3M",
    description : "Suriya, Samantha Ruth Prabhu, Nithya Menen, Ajay, Saranya Ponvannan, Girish Karnad, Sathyan. Writer & Director - Vikram K Kumar",
  },
  {
    _id : uuid(),
    title : "Passengers",
    thumbnailUrl : "https://i.ytimg.com/vi/7BWWWQzTpNU/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDpZo0ra8VZFutYttH1CjyJY3FCyg",
    channelImg : "https://yt3.ggpht.com/S4VWNJnJF_21DlC_tXhDYg6jyr4E9tJMlwn6kx49HPrh8uqNnQ3vZrIoDaaW2irhhsb-lTFQKA=s88-c-k-c0x00ffffff-no-rj",
    views: "33.2M",
    subscribers : "6.63M",
    videoLength : "02:43",
    ChannelName : "Sony Pictures Entertainment",
    categoryName : "Sci-Fi",
    youtubeId : "7BWWWQzTpNU",
    description : "Jennifer Lawrence and Chris Pratt are two passengers onboard a spaceship transporting them to a new life on another planet.  The trip takes a deadly turn when their hibernation pods mysteriously wake them 90 years before they reach their destination.  As Jim and Aurora try to unravel the mystery behind the malfunction, they begin to fall for each other, unable to deny their intense attraction... only to be threatened by the imminent collapse of the ship and the discovery of the truth behind why they woke up. ",
  },
  {
    _id : uuid(),
    title : "The Fault In Our Stars",
    thumbnailUrl : "https://i.ytimg.com/vi/9ItBvH5J6ss/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBKeTzj4_beDfFNIQbMjycq86dKiQ",
    channelImg : "https://yt3.ggpht.com/ytc/AKedOLS0_xUgI38v9jdvNVywBUODYhgnM0rU3_iJfD0ytQ=s88-c-k-c0x00ffffff-no-rj",
    views: "46M",
    subscribers : "4.4M",
    videoLength : "02:29",
    ChannelName : "20th Century Studios",
    categoryName : "Romance",
    youtubeId : "9ItBvH5J6ss",
    description : "The Fault In Our Stars | Official Trailer: Hazel (Shailene Woodley) and Gus (Ansel Elgort) are two extraordinary teenagers who share an acerbic wit, a disdain for the conventional, and a love that sweeps them -- and us -- on an unforgettable journey. Their relationship is all the more miraculous, given that they met and fell in love at a cancer support group. THE FAULT IN OUR STARS, based upon the number-one bestselling novel by John Green, explores the funny, thrilling and tragic business of being alive and in love.",
  },
  {
    _id : uuid(),
    title : "Hridayam",
    thumbnailUrl : "https://i.ytimg.com/vi/48tqyDA5Sb0/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD1rT1ii-Oi0QhNv0_9vVHH7amnfw",
    channelImg : "https://yt3.ggpht.com/ytc/AKedOLRCsDZIg-jgfZAjfXCnc3aPX9rIZz4jWYBIkmC9Dg=s88-c-k-c0x00ffffff-no-rj",
    views: "5.5M",
    subscribers : "12M",
    videoLength : "01:41",
    ChannelName : "Think Music India",
    categoryName : "Romance",
    youtubeId : "48tqyDA5Sb0",
    description : "Film: Hridayam Starring: Pranav Mohanlal, Kalyani Priyadarshan, Darshana Rajendran Directed by Vineeth Sreenivasan",
  },
  {
    _id : uuid(),
    title : "Atrangi Re",
    thumbnailUrl : "https://i.ytimg.com/vi/x3oMm5JGXZM/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD24v98NzVHGSp_icl4zt5k_9EFIA",
    channelImg : "https://yt3.ggpht.com/s-6d61eYW_qudfslNsgtFl3KYDcqOw52eWdZJ4lJyhK-F7Q8H0C4el3QAnBiHiQzi9Cx14Y5Gg=s88-c-k-c0x00ffffff-no-rj",
    views: "74M",
    subscribers : "3.67M",
    videoLength : "03:09",
    ChannelName : "DisneyPlus Hotstar",
    categoryName : "Romance",
    youtubeId : "x3oMm5JGXZM",
    description : "Ek undekhi love story aur teen atrangi log. 🏹 This Christmas get ready for a magical experience!",
  },
  {
    _id : uuid(),
    title : "Me Before You",
    thumbnailUrl : "https://i.ytimg.com/vi/Eh993__rOxA/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC01RQXMPLvtMlJ1RVAGdWncX-IrA",
    channelImg : "https://yt3.ggpht.com/ytc/AKedOLTthP-rYUtTPrGyn-rDmymOoue7BHSpkscNU083=s88-c-k-c0x00ffffff-no-rj",
    views: "29M",
    subscribers : "15.7M",
    videoLength : "02:19",
    ChannelName : "MovieClips Trailers",
    categoryName : "Romance",
    youtubeId : "Eh993__rOxA",
    description : "A girl in a small town forms an unlikely bond with a recently-paralyzed man she's taking care of",
  },
  {
    _id : uuid(),
    title : "Majili",
    thumbnailUrl : "https://i.ytimg.com/vi/R9VF3m7UiLw/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCc2QpkK1UsHd2GMedPyTOvXyxZbQ",
    channelImg : "https://yt3.ggpht.com/ytc/AKedOLQulV-sPLaXtShKruYhsaFzndu5-faC6YuEGs6ARg=s88-c-k-c0x00ffffff-no-rj",
    views: "9.5M",
    subscribers : "217K",
    videoLength : "02:12",
    ChannelName : "SHINE screens",
    categoryName : "Romance",
    youtubeId : "R9VF3m7UiLw",
    description : "MAJILI Movie Trailer on Shine Screens. Majili Latest 2019 Telugu Movie ft. Naga Chaitanya, Samantha Akkineni, and Divyansha Kaushik. The Cricket based Romantic Drama film is Directed by Shiva Nirvana. Music by Gopi Sundar. Produced by Sahu Garapati and Harish Peddi under Shine Screens. ",
  },
  {
    _id : uuid(),
    title : "Green Book",
    thumbnailUrl : "https://i.ytimg.com/vi/QkZxoko_HC0/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDDliEv-N__H1drzvmRb7Yx8_gUxg",
    channelImg : "https://yt3.ggpht.com/_xmrueXlQyPmO379bSt2BjirLWXxNOUoQn1jV0DpOlxxeCGlx9Z2L9HxfoWMgdsdIyGFh17W1A=s88-c-k-c0x00ffffff-no-rj",
    views: "13M",
    subscribers : "6.22M",
    videoLength : "02:31",
    ChannelName : "Universal Pictures",
    categoryName : "Drama",
    youtubeId : "QkZxoko_HC0",
    description : "When Tony Lip (Mortensen), a bouncer from an Italian-American neighborhood in the Bronx, is hired to drive Dr. Don Shirley (Ali), a world-class Black pianist, on a concert tour from Manhattan to the Deep South, they must rely on “The Green Book” to guide them to the few establishments that were then safe for African-Americans.  Confronted with racism, danger—as well as unexpected humanity and humor—they are forced to set aside differences to survive and thrive on the journey of a lifetime. ",
  },
  {
    _id : uuid(),
    title : "Pushpaka Vimana",
    thumbnailUrl : "https://i.ytimg.com/vi/yTQFsAgiGqo/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBtcA3ALKGm-faDRZ2fC1xwh9WRnQ",
    channelImg : "https://yt3.ggpht.com/Zkk9cFJJ6La1hiYpu3PquM8mWg8HOW897pIseQQ_ycvpNMCmWCX3rHtG0EIDVCyrQ1y_UY_x=s88-c-k-c0x00ffffff-no-rj",
    views: "470K",
    subscribers : "16.8K",
    videoLength : "01:23",
    ChannelName : "Vikyath Studios",
    categoryName : "Drama",
    youtubeId : "yTQFsAgiGqo",
    description : "Vikhyath Studios Presents the Official Trailer of  'Pushapaka Vimana'",
  },
  {
    _id : uuid(),
    title : "RRR",
    thumbnailUrl : "https://i.ytimg.com/vi/NgBoMJy386M/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAkNdOiKBGcigdlkIVu7mL_V2dl4g",
    channelImg : "https://yt3.ggpht.com/yLoFyAjWDE9wCZVMpOU_btGz8L-3iBvugSD2UDckz_WezSsZ1GvfKJnG_XN1KU3JW0wZQo1QRQ=s88-c-k-c0x00ffffff-no-rj",
    views: "75M",
    subscribers : "2.68M",
    videoLength : "03:16",
    ChannelName : "DVV Entertainment",
    categoryName : "Drama",
    youtubeId : "NgBoMJy386M",
    description : "From Indian Filmmaker SS Rajamouli (Director of Baahubali) comes India’s Biggest Action Drama #RRRMovie, in theatres March 25th, 2022",
  },
  {
    _id : uuid(),
    title : "It - Chapter 1",
    thumbnailUrl : "https://i.ytimg.com/vi/FnCdOQsX5kc/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBWFl6y1M_XXz_3ue3eMzHYuklqKw",
    channelImg : "https://yt3.ggpht.com/ytc/AKedOLR8AhEtB7GP7HrKp1mI0gYUu5HSa-HiqIpOkTOF5A=s88-c-k-c0x00ffffff-no-rj",
    subscribers : "10.5M",
    views: "66M",
    categoryName : "Horror",
    videoLength : "02:33",
    ChannelName : "Warner Bros.",
    youtubeId : "FnCdOQsX5kc",
    description : "New Line Cinema’s horror thriller “IT,” directed by Andrés Muschietti (“Mama”), is based on the hugely popular Stephen King novel of the same name, which has been terrifying readers for decades.",
  },
  {
    _id : uuid(),
    title : "Rangitaranga",
    thumbnailUrl : "https://i.ytimg.com/vi/L8wWqg2oYiQ/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB0S-4-78ETHrsoWx75MbXS-vOixg",
    channelImg : "https://yt3.ggpht.com/ytc/AKedOLRLZWchhQUl06XAkDXyQ3zBv3O-0zNUloobIrdp6A=s88-c-k-c0x00ffffff-no-rj",
    views: "1.6M",
    subscribers : "14.8k",
    videoLength : "02:45",
    ChannelName : "Anup Bhandari Cinemas",
    categoryName : "Thriller",
    youtubeId : "L8wWqg2oYiQ",
    description : "RangiTaranga is Kannada mystery thriller directed by Anup Bhandari ",
  },
  {
    _id : uuid(),
    title : "Bhool Bhulaiya 2",
    thumbnailUrl : "https://i.ytimg.com/vi/P2KRKxAb2ek/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLACIfI_rspL28sHeFS_N_wFKlyihw",
    channelImg : "https://yt3.ggpht.com/hTPDN-Yr7vQCEJ-YxDyH6OiSAMUcPd0gW40Dxy4299GFFBPh3lumCXIZhMQnOVGV6n3a1GL4BQ=s88-c-k-c0x00ffffff-no-rj",
    views: "70M",
    subscribers : "218M",
    videoLength : "03:12",
    ChannelName : "T-Series",
    categoryName : "Horror",
    youtubeId : "P2KRKxAb2ek",
    description : "Its Official, Bhool Bhulaiyaa2 all set to release on 20th MAY 2022, in cinemas near you! Starring Kartik Aaryan, Kiara Advani, and Tabu, the film has been directed by Anees Bazmee and written by Farhad Samji and Aakash Kaushik. Bhool Bhulaiyaa 2, produced by Bhushan Kumar, Murad Khetani, and Krishan Kumar under the banner of T-Series and Cine 1 Studios, is scheduled to hit the screens on 20th MAY 2022",
  },
  {
    _id : uuid(),
    title : "Sinister",
    thumbnailUrl : "https://i.ytimg.com/vi/fChx_YZUAR0/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBoCvsmhhwCVF0TnCFC5g0zkB6Xtg",
    channelImg : "https://yt3.ggpht.com/ytc/AKedOLTthP-rYUtTPrGyn-rDmymOoue7BHSpkscNU083=s88-c-k-c0x00ffffff-no-rj",
    views: "7.8M",
    subscribers : "15.7M",
    videoLength : "02:32",
    ChannelName : "MovieClips Trailer",
    categoryName : "Horror",
    youtubeId : "_kbQAJR9YWQ",
    description : "Found footage helps a true-crime novelist realize how and why a family was murdered in his new home, though his discoveries put his entire family in the path of a supernatural entity.",
  },
  {
    _id : uuid(),
    title : "Aval",
    thumbnailUrl : "https://i.ytimg.com/vi/Ft1KvQNteYY/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBE5grqkdcyciT4jalITkMHA3-Zqw",
    channelImg : "https://yt3.ggpht.com/ytc/AKedOLRoUYa8S5UF93LB0u3kBGOBgEa8MG4sGJdJQQiO=s88-c-k-c0x00ffffff-no-rj",
    views: "2.5M",
    subscribers : "8.26K",
    videoLength : "02:09",
    ChannelName : "Viacom18 Movies Tamil",
    categoryName : "Horror",
    youtubeId : "Ft1KvQNteYY",
    description : "Viacom18 Motion Pictures Presents An Etaki Entertainment Production Directed By Milind Written By - Milind, Siddharth",
  },
  {
    _id : uuid(),
    title : "Jumanji : Welcome To The Jungle",
    thumbnailUrl : "https://i.ytimg.com/vi/2QKg5SZ_35I/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAWgFtPJArpxDAjBNimVQEtfv0C6w",
    channelImg : "https://yt3.ggpht.com/S4VWNJnJF_21DlC_tXhDYg6jyr4E9tJMlwn6kx49HPrh8uqNnQ3vZrIoDaaW2irhhsb-lTFQKA=s88-c-k-c0x00ffffff-no-rj",
    views: "36M",
    subscribers : "6.36M",
    videoLength : "02:46",
    ChannelName : "Sony Pictures Entertainment",
    categoryName : "Adventure",
    youtubeId : "2QKg5SZ_35I",
    description : "The game has changed, but the legend continues. Watch the official trailer for #JUMANJI: Welcome To The Jungle now and bring home the movie NOW  Blu-ray and Digital",
  },
  {
    _id : uuid(),
    title : "Jumanji : The Next Level",
    thumbnailUrl : "https://i.ytimg.com/vi/rBxcF-r9Ibs/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBJAqDeheZCkiqpeRo0y8iYQSoVhg",
    channelImg : "https://yt3.ggpht.com/S4VWNJnJF_21DlC_tXhDYg6jyr4E9tJMlwn6kx49HPrh8uqNnQ3vZrIoDaaW2irhhsb-lTFQKA=s88-c-k-c0x00ffffff-no-rj",
    views: "45M",
    subscribers : "6.36M",
    videoLength : "02:58",
    ChannelName : "Sony Pictures Entertainment",
    categoryName : "Adventure",
    youtubeId : "2QKg5SZ_35I",
    description : "In Jumanji: The Next Level, the gang is back but the game has changed. As they return to Jumanji to rescue one of their own, they discover that nothing is as they expect. The players will have to brave parts unknown and unexplored, from the arid deserts to the snowy mountains, in order to escape the world’s most dangerous game.",
  },
  {
    _id : uuid(),
    title : "Life of Pie",
    thumbnailUrl : "https://i.ytimg.com/vi/5GbXVo9DdZo/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAfgaWKKYmmWVlIQdni6PCoL5oxuw",
    channelImg : "https://yt3.ggpht.com/ytc/AKedOLRoUYa8S5UF93LB0u3kBGOBgEa8MG4sGJdJQQiO=s88-c-k-c0x00ffffff-no-rj",
    views: "4.3M",
    subscribers : "15.7M",
    videoLength : "02:58",
    ChannelName : "MovieClips Trailers",
    categoryName : "Adventure",
    youtubeId : "3mMN693-F3U",
    description : "Director Ang Lee (Brokeback Mountain, Crouching Tiger, Hidden Dragon) creates a groundbreaking movie event about a young man who survives a tragic disaster at sea and is hurtled into an epic journey of adventure and discovery. While marooned on a lifeboat, he forms an amazing and unexpected connection with the ship's only other survivor -- a fearsome Bengal tiger.",
  },
  {
    _id : uuid(),
    title : "Ee Nagaraniki Emaindi",
    thumbnailUrl : "https://i.ytimg.com/vi/29KWCjnxQCs/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBoNRIuBngQiKnLdhxhYhjK3BVy7A",
    channelImg : "https://yt3.ggpht.com/EJrnPzRXp7BUn-NrgQjNSaxAwjqjQ26lsagm-IE_I0for-F7HInskL2m8qb8VmNtF5yrCCXXqg=s88-c-k-c0x00ffffff-no-rj",
    views: "2.8M",
    subscribers : "5.61M",
    videoLength : "01:57",
    ChannelName : "Suresh Productions",
    categoryName : "Comedy",
    youtubeId : "wERgpPK44w0",
    description : "#EeNagaranikiEmaindi is the second feature film of Tharun Bhascker who earlier directed the super hit film #Pellichoopulu. ",
  },
  {
    _id : uuid(),
    title : "Deadpool 2",
    thumbnailUrl : "https://i.ytimg.com/vi/D86RtevtfrA/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD6ZKOdQJFtICdCwxwqZ_k_ZlLKjQ",
    channelImg : "https://yt3.ggpht.com/ytc/AKedOLS0_xUgI38v9jdvNVywBUODYhgnM0rU3_iJfD0ytQ=s88-c-k-c0x00ffffff-no-rj",
    views: "49M",
    subscribers : "4.44M",
    videoLength : "02:40",
    ChannelName : "20th Century Studios",
    categoryName : "Comedy",
    youtubeId : "D86RtevtfrA",
    description : "After surviving a near fatal bovine attack, a disfigured cafeteria chef (Wade Wilson) struggles to fulfill his dream of becoming Mayberry’s hottest bartender while also learning to cope with his lost sense of taste. Searching to regain his spice for life, as well as a flux capacitor, Wade must battle ninjas, the yakuza, and a pack of sexually aggressive canines, as he journeys around the world to discover the importance of family, friendship, and flavor – finding a new taste for adventure and earning the coveted coffee mug title of World’s Best Lover. ",
  },
];
